apiVersion: v1
kind: Service
metadata:
  name: akhq
spec:
  type: {{ .Values.services.akhq.type }}
  ports:
  - name: http
    port: 9000
    targetPort: 8080
    nodePort: {{ .Values.services.akhq.nodePort }}
  selector:
    app: akhq 