apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: calloutqueuebe
  name: calloutqueuebe
spec:
  ports:
    - name: http
      port: 5135
      targetPort: 5135
      nodePort: 31315  # Optional: static NodePort for easier access
    - name: https
      port: 443
      targetPort: 7136
  selector:
    app: calloutqueuebe
  type: NodePort