apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: calloutqueuebe
  name: calloutqueuebe
spec:
  type: {{ .Values.services.calloutqueuebe.type }}
  ports:
    - name: http
      port: 5135
      targetPort: 5135
      nodePort: {{ .Values.services.calloutqueuebe.nodePort }}
    - name: https
      port: 443
      targetPort: 7136
  selector:
    app: calloutqueuebe