apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: calloutqueuebe
  name: calloutqueuebe
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5135
      targetPort: 5135
    - name: https
      port: 443
      targetPort: 7136
  selector:
    app: calloutqueuebe