apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: calloutqueuebe
  name: calloutqueuebe
spec:
  minReadySeconds: 60
  replicas: 3
  selector:
    matchLabels:
      app: calloutqueuebe
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: calloutqueuebe
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: calloutqueuebe
        - secretRef:
            name: calloutqueuebe
        image: '{{ .Values.images.calloutqueuebe }}'
        imagePullPolicy: IfNotPresent
        name: calloutqueuebe
        ports:
        - containerPort: 5135
          name: http
        - containerPort: 7136
          name: https
      terminationGracePeriodSeconds: 180