apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: calloutqueuebe
  name: calloutqueuebe
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 0
  - name: https
    port: 8443
    targetPort: 0
  selector:
    app: calloutqueuebe
  type: ClusterIP