apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: grafana
  name: grafana
spec:
  type: {{ .Values.services.grafana.type }}
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: {{ .Values.services.grafana.nodePort }}
  selector:
    app: grafana