apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: grafana
  name: grafana
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: grafana
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: grafana
        image: '{{ .Values.images.grafana }}'
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          name: http
      terminationGracePeriodSeconds: 180