apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: k6
  name: k6
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: k6
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: k6
    spec:
      containers:
      - args:
        - run
        - --address
        - 0.0.0.0:6565
        - --vus
        - "10"
        - --duration
        - 30s
        - /scripts/dist/smoke_test.js
        envFrom:
        - configMapRef:
            name: k6
        image: '{{ .Values.images.k6 }}'
        imagePullPolicy: IfNotPresent
        name: k6
        ports:
        - containerPort: 6565
          name: http
        - containerPort: 5665
          name: k6-dashboard
      terminationGracePeriodSeconds: 180