apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: k6
  name: k6
spec:
  ports:
  - name: http
    port: 6565
    targetPort: 0
  - name: k6-dashboard
    port: 5665
    targetPort: 0
  selector:
    app: k6
  type: ClusterIP