apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app: kafkaservice
  name: kafkaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaservice
  serviceName: kafkaservice
  template:
    metadata:
      annotations: {}
      labels:
        app: kafkaservice
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: kafkaservice
        image: '{{ .Values.images.kafkaservice }}'
        imagePullPolicy: IfNotPresent
        name: kafkaservice
        ports:
        - containerPort: 9092
          name: tcp
        - containerPort: 9093
          name: internal
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: calloutqueue-apphost-aacd00fd31-kafkaservice-data
      terminationGracePeriodSeconds: 180
  volumeClaimTemplates:
  - metadata:
      name: calloutqueue-apphost-aacd00fd31-kafkaservice-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi