apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: kafkaservice
  name: kafkaservice
spec:
  ports:
  - name: tcp
    port: 9092
    targetPort: 0
  - name: internal
    port: 9093
    targetPort: 0
  selector:
    app: kafkaservice
  type: ClusterIP