apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: kafkaservice
  name: kafkaservice
spec:
  type: {{ .Values.services.kafkaservice.type }}
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: {{ .Values.services.kafkaservice.nodePort }}
  selector:
    app: kafkaservice