apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: argocd
  labels:
    app: kafka-cli
spec:
  containers:
  - name: kafka-cli
    image: bitnami/kafka:latest
    command: ["sleep", "infinity"]
