apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    metadata:
      annotations: {}
      labels:
        app: kafka
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: kafka
        image: '{{ .Values.images.kafka }}'
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
          name: tcp
        - containerPort: 9093
          name: internal
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: calloutqueue-apphost-aacd00fd31-kafka-data
      terminationGracePeriodSeconds: 180
  volumeClaimTemplates:
  - metadata:
      name: calloutqueue-apphost-aacd00fd31-kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi