apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: kafkaservice
  name: kafkaservice
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafkaservice