apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: otelcollector
  name: otelcollector
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
  selector:
    app: otelcollector