apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: otelcollector
  name: otelcollector
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: otelcollector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: otelcollector
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: otelcollector
        image: '{{ .Values.images.otelcollector }}'
        imagePullPolicy: IfNotPresent
        name: otelcollector
        ports:
        - containerPort: 4317
          name: grpc
        - containerPort: 4318
          name: http
      terminationGracePeriodSeconds: 180