apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: prometheus
  name: prometheus
spec:
  type: {{ .Values.services.prometheus.type }}
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: {{ .Values.services.prometheus.nodePort }}
  selector:
    app: prometheus