apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: prometheus
  name: prometheus
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: prometheus
    spec:
      containers:
      - args:
        - --web.enable-otlp-receiver
        - --config.file=/etc/prometheus/prometheus-config.yaml
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --storage.tsdb.path=/prometheus
        - --web.enable-lifecycle
        - --web.route-prefix=/
        - --enable-feature=exemplar-storage
        - --enable-feature=otlp-write-receiver
        envFrom:
        - configMapRef:
            name: prometheus
        image: '{{ .Values.images.prometheus }}'
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          name: http
      terminationGracePeriodSeconds: 180