apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: Prometheus
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: prometheus
  name: prometheus