apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: prometheus
  name: prometheus
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus