apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: default

data:
  prometheus-config.yaml: |
    # ... existing code ...
    # The full content of prometheus-config.yaml will be inserted here.
