apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: redis
  name: redis
spec:
  type: {{ .Values.services.redis.type }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.services.redis.nodePort }}
  selector:
    app: redis