apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: rolloutfe
  name: rolloutfe
spec:
  ports:
  - name: http
    port: 8980
    targetPort: 8980
  selector:
    app: rolloutfe
  type: ClusterIP