apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: rolloutfe
  name: rolloutfe
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: rolloutfe
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: rolloutfe
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: rolloutfe
        image: '{{ .Values.images.rolloutfe }}'
        imagePullPolicy: IfNotPresent
        name: rolloutfe
        ports:
        - containerPort: 8980
          name: http
      terminationGracePeriodSeconds: 180