apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: rolloutfe
  name: rolloutfe
spec:
  type: {{ .Values.services.rolloutfe.type }}
  ports:
  - name: http
    port: 8980
    targetPort: 8980
    nodePort: {{ .Values.services.rolloutfe.nodePort }}
  selector:
    app: rolloutfe