apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: schemaregistry
  name: schemaregistry
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: schemaregistry