apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: schemaregistry
  name: schemaregistry
spec:
  ports:
  - name: primary
    port: 8081
    targetPort: 0
  selector:
    app: schemaregistry
  type: ClusterIP