apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: SchemaRegistry
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafkaservice:9092
  SCHEMA_REGISTRY_HOST_NAME: schema-registry

kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: schemaregistry
  name: schemaregistry