apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: schemaregistry
  name: schemaregistry
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: schemaregistry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: schemaregistry
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: schemaregistry
        image: '{{ .Values.images.schemaregistry }}'
        imagePullPolicy: IfNotPresent
        name: schemaregistry
        ports:
        - containerPort: 8081
          name: primary
      terminationGracePeriodSeconds: 180