apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: schemaregistry
  name: schemaregistry
spec:
  type: {{ .Values.services.schemaregistry.type }}
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.services.schemaregistry.nodePort }}
  selector:
    app: schemaregistry