apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: seq
  name: seq
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: seq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: seq
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: seq
        image: '{{ .Values.images.seq }}'
        imagePullPolicy: IfNotPresent
        name: seq
        ports:
        - containerPort: 80
          name: seq
      terminationGracePeriodSeconds: 180