apiVersion: v1
data:
  ACCEPT_EULA: "Y"
  SEQ_FIRSTRUN_ADMINPASSWORD: "12345"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcollector:4317
  OTEL_SERVICE_NAME: Seq
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: seq
  name: seq