apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: seq
  name: seq
spec:
  type: {{ .Values.services.seq.type }}
  ports:
    - name: http
      port: 5341
      targetPort: 5341
      nodePort: {{ .Values.services.seq.nodePort }}
  selector:
    app: seq