apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: sqlserver
  name: sqlserver
spec:
  type: {{ .Values.services.sqlserver.type }}
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
      nodePort: {{ .Values.services.sqlserver.nodePort }}
  selector:
    app: sqlserver