apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: sqlserver
  name: sqlserver
spec:
  type: ClusterIP
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
  selector:
    app: sqlserver