apiVersion: v1
data:
  ACCEPT_EULA: "Y"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcollector:4317
  OTEL_SERVICE_NAME: SqlServer
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: sqlserver
  name: sqlserver