apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: sqlserver
  name: sqlserver
spec:
  ports:
  - name: tcp
    port: 1433
    targetPort: 0
  selector:
    app: sqlserver
  type: ClusterIP