{
 "title": "ASP.NET Core application Running on OpenShift Origin",
 "description": "ASP.NET Core application Running on OpenShift Origin, metrics provided by prometheus lib",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(dotnet_threadpool_scheduling_delay_seconds_bucket, instance)"
   },
   {
    "name": "job",
    "query": "label_values(dotnet_threadpool_scheduling_delay_seconds_bucket{instance=~\"$instance\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Current Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TurkuazGO Pod Count (API)",
   "type": "singlestat",
   "description": "TurkuazGO_Environment_ProcessesCount count of processes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_Environment_ProcessesCount{job=\"$job\"}",
     "legendFormat": "{{ComputerName}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "% Paused time",
   "type": "singlestat",
   "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_gc_pause_ratio" }
   ]
  },
  {
   "title": "% JIT CPU consumption",
   "type": "singlestat",
   "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_jit_cpu_ratio" }
   ]
  },
  {
   "title": "process num threads",
   "type": "singlestat",
   "description": "process_num_threads Total number of threads",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_num_threads",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "process_num_threads",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap size (all generations)",
   "type": "singlestat",
   "description": "dotnet_gc_heap_size_bytes The current size of all heaps (only updated after a garbage collection)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(dotnet_gc_heap_size_bytes)" }
   ]
  },
  {
   "title": "% GC CPU consumption",
   "type": "singlestat",
   "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_gc_cpu_ratio" }
   ]
  },
  {
   "title": "Num Active threads",
   "type": "singlestat",
   "description": "The number of active threads in the thread pool",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "dotnet_threadpool_num_threads" }
   ]
  },
  {
   "title": "Durations requests to endpoints [GET]",
   "type": "singlestat",
   "description": "Durations requests to endpoints",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_RequestDuration_Method",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory / Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "dotnet_gc_heap_size_bytes", "legendFormat": "gen {{gc_generation}}" }
     ]
    },
    {
     "title": "Bytes allocated (by heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dotnet_gc_allocated_bytes_total{gc_heap=\"loh\"}[$__interval])) by (gc_heap)",
       "legendFormat": "Large object heap (objects > 85KB)"
      },
      {
       "expr": "sum(rate(dotnet_gc_allocated_bytes_total{gc_heap=\"soh\"}[$__interval])) by (gc_heap)",
       "legendFormat": "Small object heap"
      }
     ]
    },
    {
     "title": "GC CPU + pause ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "dotnet_gc_cpu_ratio", "legendFormat": "GC CPU %" },
      { "expr": "dotnet_gc_pause_ratio", "legendFormat": "GC Pause %" }
     ]
    },
    {
     "title": "Number of GC collections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dotnet_gc_collection_seconds_count[$__interval])) by (gc_generation, gc_type)",
       "legendFormat": "gen {{gc_generation}}: {{gc_type}}"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
       "legendFormat": "Median"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
       "legendFormat": "90th %"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
       "legendFormat": "99th %"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Average GC duration (by generation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dotnet_gc_collection_seconds_sum[$__interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count[$__interval])) by (gc_generation) ",
       "legendFormat": "{{gc_generation}}"
      }
     ]
    }
   ]
  },
  { "title": "Application Side Deep Dive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "dotnet contention total",
   "type": "singlestat",
   "description": "The number of locks contended",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "dotnet_contention_total",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "dotnet contention total time spent",
   "type": "singlestat",
   "description": "The total amount of time spent contending locks",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "dotnet_contention_seconds_total",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "jit method count [dynamic]",
   "type": "singlestat",
   "description": "Total number of methods compiled by the JIT compiler",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "dotnet_jit_method_total{dynamic=\"true\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "jit method count [non-dynamic]",
   "type": "singlestat",
   "description": "Total number of methods compiled by the JIT compiler",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "dotnet_jit_method_total{dynamic=\"false\"} ",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod RequestDuration by Endpoint [GET]",
   "type": "graph",
   "description": "TurkuazGO_RequestDuration_Method_Endpoint Durations requests to endpoints",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_RequestDuration_Method_Endpoint {method=\"GET\"}",
     "legendFormat": "{{ComputerName}} {{endpoint}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total memory consumption by process set",
   "type": "singlestat",
   "description": "The total amount of physical memory the associated process is using, in mbs",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_working_set_bytes",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total CPU Time",
   "type": "grafana-piechart-panel",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_cpu_seconds_total{job=\"$job\"}",
     "legendFormat": "cpu time",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total HTTP Reqs",
   "type": "singlestat",
   "description": "Provides the count of HTTP requests that have been processed by the ASP.NET Core pipeline.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "http_requests_received_total{method=\"GET\",job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Failed Reqs",
   "type": "singlestat",
   "description": "Number of http operations that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_FailedResponseCount",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Reqs",
   "type": "graph",
   "description": "Total Counts requests to endpoints",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_TotalRequestCount{job=\"$job\"}",
     "legendFormat": "{{ComputerName}} {{endpoint}} {{method}} {{status}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Thread pool adjustment reasons",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_adjustments_total[$__interval])) by (adjustment_reason )",
     "legendFormat": "{{adjustment_reason}}"
    }
   ]
  },
  {
   "title": "Total Active Reqs",
   "type": "graph",
   "description": "Counts requests to endpoints",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_TotalActiveRequestCount{method=\"GET\"}",
     "legendFormat": "{{ComputerName}} {{endpoint}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Thread pool scheduling latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "90th %"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "99th %"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(dotnet_threadpool_scheduling_delay_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "dotnet_gc_collection_seconds_bucket",
   "type": "graph",
   "description": "dotnet_gc_collection_seconds The amount of time spent running garbage collections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dotnet_gc_collection_seconds_bucket[10m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dotnet_gc_collection_seconds_bucket[10m])) by (le))",
     "legendFormat": "90th %"
    }
   ]
  },
  {
   "title": "dotnet_gc_collection_seconds_bucket_increase_status",
   "type": "graph",
   "description": "increase series dotnet_gc_collection_seconds The amount of time spent running garbage collections",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(increase(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "90th %"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(1.0, sum(increase(dotnet_gc_collection_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "100th %"
    }
   ]
  },
  {
   "title": "Total GC Pause Seconds",
   "type": "graph",
   "description": "The amount of time execution was paused for garbage collection",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.5, sum(rate(dotnet_gc_pause_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Median",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dotnet_gc_pause_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "% 90"
    }
   ]
  },
  { "title": "System Side Deep Dive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Start time of the process since unix epoch",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 51 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_start_time_seconds{job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Process Private Memory Size",
   "type": "singlestat",
   "description": "Process private memory size",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 51 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_private_memory_bytes",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Open Handles",
   "type": "singlestat",
   "description": "Number of open handles",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_open_handles{job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total User and System CPU Time",
   "type": "singlestat",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 51 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "process_cpu_seconds_total{job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Num IO Threads",
   "type": "singlestat",
   "description": "The number of active threads in the IO thread pool",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "dotnet_threadpool_io_num_threads{job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Page Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 51 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_Environment_SystemPageSize{job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Size of Working Set",
   "type": "singlestat",
   "description": "[Working Set Size (WSS) is how much memory an application needs to keep working.]\n\nSize of Working Set",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 51 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_Environment_WorkingSetSize{job=\"$job\"}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS Memory",
   "type": "singlestat",
   "description": "TurkuazGO_Environment_LinuxOSMemory Linux OS Memory",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_Environment_LinuxOSMemory",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Total Memory",
   "type": "singlestat",
   "description": "TurkuazGO_Environment_GCTotalMemory total memory of gc",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "TurkuazGO_Environment_GCTotalMemory ",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}