{
 "title": "CalloutQueue metrics with Exemplars",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the use of metric exemplars.\nExemplars can be used to look up a trace in Jaeger.\nOnly the most recent exemplars may still be available in Jaeger.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "CalloutQueue Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Get Segment Queue Items Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route=\"api/CalloutQueue/segment/{segmentId:int}/queue-items\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95th Pct Get Segment Queue Items Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route=\"api/CalloutQueue/segment/{segmentId:int}/queue-items\"}[$__rate_interval])))",
     "legendFormat": "p95 Get Segment Queue Items"
    }
   ]
  },
  { "title": "AddItem Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "AddItem Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_cart_add_item_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}